baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Hugo Site'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'News'
pageRef = '/news'
weight = 20

[[menus.main]]
name = 'Live'
pageRef = '/live'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
